### ISSUE TITLE
Stubs for all tools in no-op

### ISSUE THREAD

**Issue by markonovina** [infinum/android-sentinel#13]
## :warning: Is your feature request related to a problem? Please describe
When using no-op for tools with a custom implementation of some tool (eg. AnalyticsTool) we need to stub that.

## :bulb: Describe the solution you'd like
Please add stubs in no-op for all tools. In that case, when no-op is used we don't need to implement stubs for our custom tools.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ x] No

**Comment by bojankoma** [comment]
HAs been done and released in 1.0.4.
