### ISSUE TITLE
Crash notifications don't work on Android 13

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android-sentinel#45]
## :writing_hand: Describe the bug
When turning on crash notifications on Android 13 (the app must _target_ 13 _and_ run on an Android 13 device), and force-crashing the app, no notification for the crash is shown.

## :bomb: Steps to reproduce
1. Turn on the three toggles under "Crash monitor" in Sentinel settings
2. Throw a runtime exception to crash the app

## :wrench: Expected behavior
A notification should be displayed, which, upon clicking, opens a new screen with crash data.

## :iphone: Tech info
 - Device: Pixel 7
 - OS: Android 13
 - Sentinel version: 1.3.0

## :page_facing_up: Additional context
Lint also reports the following error when analyzing an app that targets Android 13+:
```
/app/src/main/AndroidManifest.xml: Error: When targeting Android 13 or higher, posting a permission requires holding the POST_NOTIFICATIONS permission (usage from com.infinum.sentinel.ui.shared.notification.d) [NotificationPermission]
   Explanation for issues of type "NotificationPermission":
   When targeting Android 13 and higher, posting permissions requires holding
   the runtime permission android.permission.POST_NOTIFICATIONS.
```

**Comment by KCeh** [comment]
Fixed for release https://github.com/infinum/android-sentinel/releases/tag/1.3.2
