### ISSUE TITLE
Proximity trigger is active despite being turned off in AndroidManifest

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android-sentinel#46]
## :writing_hand: Describe the bug
I noticed that hovering/waving over the phone's camera triggers the Sentinel to show up even though I have it disabled in AndroidManifest.xml. However, after visiting the Sentinel's UI settings and exiting them (without changing anything), the trigger seems to stop being active.

## :bomb: Steps to reproduce
1. Cold-start the application with the proximity trigger being off in AndroidManifest.xml
2. Wave over the device -> the UI will show up
3. Go to the Settings (cog icon) -> observe that the trigger is shown as "off".
4. Exit the settings and close the Sentinel UI
5. Waving over the device no longer triggers the UI.

## :wrench: Expected behavior
The device should not react to the proximity trigger when turned off.

## :iphone: Tech info
 - Device: Pixel 7
 - OS: Android 13
 - Sentinel version: 1.3.0

**Comment by JonatanPlesko** [comment]
@simicmarin I would consider this a high-priority bug. It happens on every app startup, which is quite annoying, and everyone using development builds is affected by this.

**Comment by simicmarin** [comment]
> @simicmarin I would consider this a high-priority bug. It happens on every app startup, which is quite annoying, and everyone using development builds is affected by this.

I'll try to prioritise it. Thank you for your input 👍

**Comment by KCeh** [comment]
Fixed for release https://github.com/infinum/android-sentinel/releases/tag/1.3.2
