### ISSUE TITLE
Parse UNIX timestamp to readable date in exported logs

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android-sentinel#47]
## :warning: Is your feature request related to a problem? Please describe
While browsing logs in the Logger UI, you can see the prettified, albeit unprecise time such as:
"Oct 3, 2023 13:27:18".
However, when the logs are exported, the time format is set to the UNIX/epoch timestamp such as:
1696332438859

## :bulb: Describe the solution you'd like
Ideally, the logs could be exported in the same format as the Logcat. The above example would then be:
2023-10-03 13:27:18.091
That would give it millisecond precision while still making it readable.

## :bar_chart: Describe alternatives you've considered
The current approach does have one significant advantage - it is timezone agnostic. But this _could_ be resolved by adding the timezone to the timestamp _or_ converting it to UTC+00:00. 

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by KCeh** [comment]
Should be resolved with **new release**
