### ISSUE TITLE
Cannot install both debug and release versions of the app with Sentinel

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android-sentinel#76]
## :writing_hand: Describe the bug

When I already have a debug version of my app installed on a phone and then attempt to install the release version, I get the following error in Android Studio:

```
Error running 'Sample.app' 
The application could not be installed: INSTALL_FAILED_DUPLICATE_PERMISSION 
Installation failed due to: 'Error code: 'INSTALL_FAILED_DUPLICATE_PERMISSION', message='INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.sample.app.dev attempting to redeclare permission com.infinum.sentinel.permission.ACCESS_SENTINEL already owned by com.sample.app.dev.debug'' 
List of apks:
[0] '/app/build/intermediates/extracted_apks/devRelease/extractApksFromBundleForDevRelease/base-arm64_v8a.apk' 
[1] '/app/build/intermediates/extracted_apks/devRelease/extractApksFromBundleForDevRelease/base-xxhdpi.apk' 
[2] '/app/build/intermediates/extracted_apks/devRelease/extractApksFromBundleForDevRelease/base-master.apk'
```

## :bomb: Steps to reproduce
1. Install a debug version of the app
2. Attempt to install a release version of the app. Sentinel must be included in both release and debug version.

## :wrench: Expected behavior
It should be possible to install multiple flavors and build types of the same app containing Sentinel on the same phone.

## :iphone: Tech info
 - Device: Pixel 7
 - OS: Android 14
 - Sentinel version: 1.4.0

## :page_facing_up: Additional context
I believe this issue was introduced in 1.4.0 in the following commit: 73ff9c9eff960c014773845517ca79f0ee22231a
I expect leveraging the app ID to make sure the permission is unique across different build types and flavors is the way to go, but I'm not exactly sure how and if it is achievable.

**Comment by KCeh** [comment]
> I believe this issue was introduced in 1.4.0 in the following commit: https://github.com/infinum/android-sentinel/commit/73ff9c9eff960c014773845517ca79f0ee22231a
> I expect leveraging the app ID to make sure the permission is unique across different build types and flavors is the way to go, but I'm not exactly sure how and if it is achievable.

Correct. We will look into the possibility of improving the current setup. If that is not possible, simple rollback for permission should be enough for hotfix

**Comment by KCeh** [comment]
There might be a workaround by using `applicationId` in the permission name.
But it seems solution is not bulletproof. If user doesn't set `applicationIdSuffix`for different variants there could be issues.
I will remove permission and release hotfix.

**Comment by KCeh** [comment]
Should be resolved in [latest release ](https://github.com/infinum/android-sentinel/releases/tag/1.4.1)
